# Sử dụng image Node.js chính thức để xây dựng ứng dụng
FROM node:18 AS build

# Thiết lập thư mục làm việc trong container
WORKDIR /app

# Sao chép file package.json và package-lock.json vào container
COPY package*.json ./

# Cài đặt dependencies
RUN npm install

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Xây dựng ứng dụng với Vite
RUN npm run build

# Sử dụng Nginx làm server cho ứng dụng
FROM nginx:stable-alpine

# Sao chép file cấu hình Nginx nếu cần (tùy chọn)
# COPY nginx.conf /etc/nginx/nginx.conf

# Sao chép file build vào thư mục mặc định của Nginx để phục vụ ứng dụng
COPY --from=build /app/dist /usr/share/nginx/html

# Mở port 80
EXPOSE 80

# Chạy Nginx
CMD ["nginx", "-g", "daemon off;"]



# # Sử dụng image Node.js chính thức để xây dựng ứng dụng
# FROM node:18

# # Thiết lập thư mục làm việc trong container
# WORKDIR /app

# # Sao chép file package.json và package-lock.json vào container
# COPY package*.json ./

# # Cài đặt dependencies
# RUN npm install

# # Mở port Vite server
# EXPOSE 5173

# # Lệnh mặc định để chạy Vite ở chế độ development
# CMD ["npm", "run", "dev"]

